services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      # --- KRaft 模式配置 ---
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://192.168.153.130:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LOG_DIRS=/bitnami/kafka/data

  order-system:
    build: 
      context: /app/order-system
      dockerfile: Dockerfile
    container_name: order-system
    ports:
      - "8080:8080"
    environment:
      # ✅ 配置 MySQL 地址（使用服务名 'mysql' 作为 host）
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/order?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123456
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver

      # ✅ 配置 Redis 地址
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
      - SPRING_REDIS_DATABASE=0

      # ✅ 配置 Kafka 地址
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - SPRING_KAFKA_PRODUCER_VALUE-SERIALIZER=org.apache.kafka.common.serialization.StringSerializer
      - SPRING_KAFKA_PRODUCER_KEY-SERIALIZER=org.apache.kafka.common.serialization.StringSerializer
      - SPRING_KAFKA_PRODUCER_RETRIES=3
      - SPRING_KAFKA_PRODUCER_BATCH-SIZE=16384
      - SPRING_KAFKA_PRODUCER_BUFFER-MEMORY=33554432
      - SPRING_KAFKA_CONSUMER_KEY-DESERIALIZER=org.apache.kafka.common.serialization.StringDeserializer
      - SPRING_KAFKA_CONSUMER_VALUE-DESERIALIZER=org.apache.kafka.common.serialization.StringDeserializer
      - SPRING_KAFKA_CONSUMER_MAX-POLL-RECORDS=1000
      - SPRING_KAFKA_CONSUMER_ENABLE-AUTO-COMMIT=true
      - SPRING_KAFKA_CONSUMER_AUTO-OFFSET-RESET=latest
      - SPRING_KAFKA_CONSUMER_AUTO-COMMIT-INTERVAL=100
    depends_on:
      - mysql
      - redis
      - kafka

  order-worker:
    build: 
      context: /app/order-worker
      dockerfile: Dockerfile
    container_name: order-worker
    ports:
      - "8081:8081"
    environment:
      # ✅ 配置 MySQL 地址（使用服务名 'mysql' 作为 host）
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/order?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123456
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver

      # ✅ 配置 Redis 地址
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
      - SPRING_REDIS_DATABASE=0

      # ✅ 配置 Kafka 地址
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - SPRING_KAFKA_PRODUCER_VALUE-SERIALIZER=org.apache.kafka.common.serialization.StringSerializer
      - SPRING_KAFKA_PRODUCER_KEY-SERIALIZER=org.apache.kafka.common.serialization.StringSerializer
      - SPRING_KAFKA_PRODUCER_RETRIES=3
      - SPRING_KAFKA_PRODUCER_BATCH-SIZE=16384
      - SPRING_KAFKA_PRODUCER_BUFFER-MEMORY=33554432
      - SPRING_KAFKA_CONSUMER_KEY-DESERIALIZER=org.apache.kafka.common.serialization.StringDeserializer
      - SPRING_KAFKA_CONSUMER_VALUE-DESERIALIZER=org.apache.kafka.common.serialization.StringDeserializer
      - SPRING_KAFKA_CONSUMER_MAX-POLL-RECORDS=1000
      - SPRING_KAFKA_CONSUMER_ENABLE-AUTO-COMMIT=true
      - SPRING_KAFKA_CONSUMER_AUTO-OFFSET-RESET=latest
      - SPRING_KAFKA_CONSUMER_AUTO-COMMIT-INTERVAL=100
    depends_on:
      - kafka
      - mysql

  alarm-system:
    build: 
      context: /app/alarm-system
      dockerfile: Dockerfile
    container_name: alarm-system
    ports:
      - "8082:8082"
    environment:
      # ✅ 配置 MySQL 地址（使用服务名 'mysql' 作为 host）
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/order?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123456
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver

      # ✅ 配置 Kafka 地址
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - SPRING_KAFKA_PRODUCER_VALUE-SERIALIZER=org.apache.kafka.common.serialization.StringSerializer
      - SPRING_KAFKA_PRODUCER_KEY-SERIALIZER=org.apache.kafka.common.serialization.StringSerializer
      - SPRING_KAFKA_PRODUCER_RETRIES=3
      - SPRING_KAFKA_PRODUCER_BATCH-SIZE=16384
      - SPRING_KAFKA_PRODUCER_BUFFER-MEMORY=33554432
      - SPRING_KAFKA_CONSUMER_KEY-DESERIALIZER=org.apache.kafka.common.serialization.StringDeserializer
      - SPRING_KAFKA_CONSUMER_VALUE-DESERIALIZER=org.apache.kafka.common.serialization.StringDeserializer
      - SPRING_KAFKA_CONSUMER_MAX-POLL-RECORDS=1000
      - SPRING_KAFKA_CONSUMER_ENABLE-AUTO-COMMIT=true
      - SPRING_KAFKA_CONSUMER_AUTO-OFFSET-RESET=latest
      - SPRING_KAFKA_CONSUMER_AUTO-COMMIT-INTERVAL=100
    depends_on:
      - kafka
      - mysql
  timertask-system:
    build: 
      context: /app/timertask-system
      dockerfile: Dockerfile
    container_name: timertask-system
    ports:
      - "8083:8083"
    environment:
      # ✅ 配置 MySQL 地址（使用服务名 'mysql' 作为 host）
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/order?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123456
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver

      # ✅ 配置 Redis 地址
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
      - SPRING_REDIS_DATABASE=0
    depends_on:
      - redis
      - mysql