server:
  port: 8080
  servlet:
    context-path: /orderSystem
spring:
  datasource:
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    hikari:
      auto-commit: true
      pool-name: order-system-hikari
      #最大连接数上限
      maximum-pool-size: 50
      #获取连接超时时间
      connection-timeout: 5000
      #最小空闲连接数
      minimum-idle: 10
      #空闲连接存活时间
      idle-timeout: 600000
      #连接最大生命周期
      max-lifetime: 1800000
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}
    producer:
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      retries: 3
      batch-size: 16384
      buffer-memory: 33554432
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      max-poll-records: 1000
      enable-auto-commit: true
      auto-offset-reset: latest
      auto-commit-interval: 100

  redis:
    host: ${SPRING_REDIS_HOST}
    port: ${SPRING_REDIS_PORT}






