server:
  port: 8082
  servlet:
    context-path: /alarm

lark:
  webhook:
    alert: https://open.larksuite.com/open-apis/bot/v2/hook/8546725c-958b-44da-bebd-7e410244df7d

spring:
  datasource:
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    hikari:
      auto-commit: true
      pool-name: alarm-system-hikari
      #最大连接数上限
      maximum-pool-size: 20
      #获取连接超时时间
      connection-timeout: 5000
      #最小空闲连接数
      minimum-idle: 50
      #空闲连接存活时间
      idle-timeout: 300000
      #连接最大生命周期
      max-lifetime: 1800000
  kafka:
    bootstrap-servers:  ${SPRING_KAFKA_BOOTSTRAP_SERVERS}
    producer:
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      retries: 3
      batch-size: 16384
      buffer-memory: 33554432
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      max-poll-records: 1000
      enable-auto-commit: false
      auto-offset-reset: latest
      auto-commit-interval: 100
    listener:
      type: batch
      ack-mode: manual_immediate